<?xml version="1.0"?>
<robot name="milo" xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:gz="http://gazebosim.org/schema">

  <!-- Include useful macros -->
  <xacro:include filename="inertial_macros.xacro" />
  <xacro:include filename="colors.xacro" />

  <!-- Define the robot's properties -->
  <xacro:property name="chassis_length" value="0.26" />
  <xacro:property name="chassis_width" value="0.26" />
  <xacro:property name="chassis_height" value="0.05" />
  <xacro:property name="chassis_mass" value="0.350" />
  <xacro:property name="wheel_axis_offset_x" value="0.04" />
  <xacro:property name="wheel_axis_offset_z" value="0.01" />
  <xacro:property name="wheel_radius" value="0.03" />
  <xacro:property name="wheel_thickness" value="0.025" />
  <xacro:property name="ldr_inter_offset" value="0.025" />
  <xacro:property name="ldr_height" value="0.005" />
  <xacro:property name="ldr_radius" value="0.035"/>


  <!-- World link without inertia required by rviz -->
  <link name="base_link">
  </link>


  <!-- CHASSIS -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="chassis_link" />
    <origin xyz="${-chassis_length/2} 0.0 0.1" rpy="0.0 0.0 0.0" />
  </joint>


  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
      <material name="white" />
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}"
      z="${chassis_height}">
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
    </xacro:inertial_box>
  </link>

  <!-- Chassis center link to link the LDRs to -->
  <joint name="chassis_center_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="chassis_center_link"/>
    <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
  </joint>
  
  <link name="chassis_center_link"></link>

  <!-- WHEELS (looked at from the front of the robot) -->
  <joint name="BR_wheel_joint" type="continuous">
    <parent link="chassis_link" />
    <child link="BR_wheel_link" />
    <origin xyz="${wheel_axis_offset_x} ${chassis_width/2 + wheel_thickness} ${wheel_axis_offset_z}" rpy="${-pi/2} 0 0" />
    <axis xyz="0.0 0.0 -1.0" />
    <limit effort="10000" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name="BR_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${-wheel_thickness/2}" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${-wheel_thickness/2}" />
    </collision>
    <xacro:inertial_cylinder mass="0.020" radius="${wheel_radius}" length="${wheel_thickness}">
      <origin xyz="0 0 ${-wheel_thickness/2}" />
    </xacro:inertial_cylinder>
  </link>

  <joint name="BL_wheel_joint" type="continuous">
    <parent link="chassis_link" />
    <child link="BL_wheel_link" />
    <origin xyz="${wheel_axis_offset_x} ${-chassis_width/2} ${wheel_axis_offset_z}"
      rpy="${pi/2} 0 0" />
    <axis xyz="0.0 0.0 1.0" />
    <limit effort="10000" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name="BL_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${wheel_thickness/2}" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${wheel_thickness/2}" />
    </collision>
    <xacro:inertial_cylinder mass="0.020" radius="${wheel_radius}" length="${wheel_thickness}">
      <origin xyz="0 0 ${wheel_thickness/2}" />
    </xacro:inertial_cylinder>
  </link>

  <joint name="FL_wheel_joint" type="continuous">
    <parent link="chassis_link" />
    <child link="FL_wheel_link" />
    <origin xyz="${chassis_length - wheel_axis_offset_x} ${-chassis_width/2} ${wheel_axis_offset_z}"
      rpy="${pi/2} 0 0" />
    <axis xyz="0.0 0.0 1.0" />
    <limit effort="10000" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name="FL_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${wheel_thickness/2}" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${wheel_thickness/2}" />
    </collision>
    <xacro:inertial_cylinder mass="0.020" radius="${wheel_radius}" length="${wheel_thickness}">
      <origin xyz="0 0 ${wheel_thickness/2}" />
    </xacro:inertial_cylinder>
  </link>

  <joint name="FR_wheel_joint" type="continuous">
    <parent link="chassis_link" />
    <child link="FR_wheel_link" />
    <origin xyz="${chassis_length - wheel_axis_offset_x} ${chassis_width/2 + wheel_thickness} ${wheel_axis_offset_z}"
      rpy="${-pi/2} 0 0" />
    <axis xyz="0.0 0.0 -1.0" />
    <limit effort="10000" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name="FR_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${-wheel_thickness/2}" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <origin xyz="0 0 ${-wheel_thickness/2}" />
    </collision>
    <xacro:inertial_cylinder mass="0.020" length="${wheel_thickness}" radius="${wheel_radius}">
      <origin xyz="0 0 ${-wheel_thickness/2}" />
    </xacro:inertial_cylinder>
  </link>

  <!-- LDR PLACEMENTS -->
  <xacro:macro name="ldr_joint_and_link" params="name angle">
    <joint name="${name}_joint" type="fixed">
      <parent link="chassis_center_link"/>
      <child link="${name}_link"/>
      <origin xyz="${ldr_radius * cos(angle)} ${ldr_radius * sin(angle)} 0" rpy="0 ${pi/2} 0"/>
    </joint>

    <link name="${name}_link">
      <visual>
        <geometry>
          <box size="${ldr_height} ${ldr_height} ${ldr_height}"/>
        </geometry>
        <material name="red"/>
        <origin xyz="0 0 ${-ldr_height/2}"/>
      </visual>

      <collision>
        <geometry>
          <box size="${ldr_height} ${ldr_height} ${ldr_height}"/>
        </geometry>
      </collision>

      <xacro:inertial_box mass="0.001" x="${ldr_height}" y="${ldr_height}" z="${ldr_height}">
        <origin xyz="0 0 ${-ldr_height/2}"/>
      </xacro:inertial_box>
    </link>
  </xacro:macro>

  <xacro:ldr_joint_and_link name="ldr1" angle="0"/>
  <xacro:ldr_joint_and_link name="ldr2" angle="${pi/4}"/>
  <xacro:ldr_joint_and_link name="ldr3" angle="${pi/2}"/>
  <xacro:ldr_joint_and_link name="ldr4" angle="${3*pi/4}"/>
  <xacro:ldr_joint_and_link name="ldr5" angle="${pi}"/>
  <xacro:ldr_joint_and_link name="ldr6" angle="${5*pi/4}"/>
  <xacro:ldr_joint_and_link name="ldr7" angle="${3*pi/2}"/>
  <xacro:ldr_joint_and_link name="ldr8" angle="${7*pi/4}"/>
  

  <!-- GAZEBO information -->
  <gazebo>
    <plugin
      filename="gz-sim-mecanum-drive-system"
      name="gz::sim::systems::MecanumDrive">
      <front_left_joint>FL_wheel_joint</front_left_joint>
      <front_right_joint>FR_wheel_joint</front_right_joint>
      <back_left_joint>BL_wheel_joint</back_left_joint>
      <back_right_joint>BR_wheel_joint</back_right_joint>
      <wheel_separation>0.26</wheel_separation> <!-- Chassis width -->
      <wheelbase>0.18</wheelbase> <!-- Chassis length - 2*wheel_offset_x -->
      <wheel_radius>0.03</wheel_radius>
      <min_acceleration>-5</min_acceleration>
      <max_acceleration>5</max_acceleration>
    </plugin>
  </gazebo>

  <gazebo reference="ldr1_link">
    <sensor name="0" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr1</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr2_link">
    <sensor name="1" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr2</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr3_link">
    <sensor name="2" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr3</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr4_link">
    <sensor name="3" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr4</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr5_link">
    <sensor name="4" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr5</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr6_link">
    <sensor name="5" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr6</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr7_link">
    <sensor name="6" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr7</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="ldr8_link">
    <sensor name="7" type="camera">
      <camera>
        <horizontal_fov>1.25</horizontal_fov>
        <image>
          <width>10</width>
          <height>8</height>
        </image>
        <clip> <!-- The range of the camera-->
          <near>0.001</near>
          <far>0.2</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>          
          <stddev>0.2</stddev>    
        </noise>
      </camera>
      <topic>milo/ldr8</topic>
      <update_rate>7</update_rate>
    </sensor>
  </gazebo>

  <!-- STEP 6 - Gazebo frictions and colors -->
  <gazebo reference='FL_wheel_link'>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.5</mu2>
            <fdir1 gz:expressed_in="base_link">1 -1 0</fdir1>
          </ode>
        </friction>
      </surface>
    </collision>
  </gazebo>

  <gazebo reference='BL_wheel_link'>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.5</mu2>
            <fdir1 gz:expressed_in="base_link">1 1 0</fdir1>
          </ode>
        </friction>
      </surface>
    </collision>
  </gazebo>

  <gazebo reference='FR_wheel_link'>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.5</mu2>
            <fdir1 gz:expressed_in="base_link">1 1 0</fdir1>
          </ode>
        </friction>
      </surface>
    </collision>
  </gazebo>

  <gazebo reference='BR_wheel_link'>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.5</mu2>
            <fdir1 gz:expressed_in="base_link">1 -1 0</fdir1>
          </ode>
        </friction>
      </surface>
    </collision>
  </gazebo>

  <gazebo reference="chassis_link">
    <mu1>0.000002</mu1>
    <mu2>0.000002</mu2>
    <!-- <material>Gazebo/Red</material> -->
  </gazebo>
</robot>